### PR TITLE
Make subgraph c++

### PR DESCRIPTION
**Pull request by afshinfard**
not to be merged with master.. only for code review

### CODE REVIEW

**Comment by afshinfard** [comment]
I should have done this just after I did port the code.. switching between languages is painful!

This code successfully works on tests, but seems to be slow on real datasets... any suggestions?!

**Comment by afshinfard** [comment]
one other alternative is to:
1- make a new subgraph with all the vertices, 
2- and then each vertex:
extract the neighbours from the original graph, and add an edge in the `subgraph` if the neighbours exists in the subgraph.

**Comment by afshinfard** [comment]
@jowong4 This is not going to be merged yet! I wanted to hear your feedback on the implementation, as this is slower than the original `create_subgraph()` function!
Although we can make it faster by using multiple threads, I was wondering if you have suggestion to make it run faster on single thread too.

**Comment by jowong4** [comment]
You could make an auxillary data structure - a set of edges. The graph currently stores it in a vector so to locate an edge takes some time. You would use the set of edges to check for presence.

**Pull request closed without merging**
