### PR TITLE
Check for white-space errors using clang-format

### PR DESCRIPTION
**Pull request by gokcedilek**

### CODE REVIEW

**Comment by sjackman** [comment]
I think this PR unintentionally included commit bdc4c76c6c27a095644fb4c9f96abee54e91baec

**Comment by gokcedilek** [comment]
Rebased onto origin/master!

**Comment by sjackman** [comment]
```
bash: clang-format: command not found
```
https://dev.azure.com/bcgsc/btl/_build/results?buildId=889

**Comment by sjackman** [comment]
```
./data/checkMx.sh data/f1chr4-head50.n100-1000.good.tsv data/f1chr4-head50.n100-1000.tsv
./physlr-filter-barcodes data/f1.indexlr.head1000.physlr.tsv -n2 -N10 -o fb-cpp
error: No such file or directory: data/f1.indexlr.head1000.physlr.tsv
```
https://dev.azure.com/bcgsc/btl/_build/results?buildId=930&view=logs&jobId=5264e576-3c6f-51f6-f055-fab409685f20&taskId=999d1e63-f491-5647-b12a-6f602a65e22e&lineStart=31&lineEnd=34&colStart=1&colEnd=1

This `make check` error seems unrelated to this PR.

**Comment by sjackman** [comment]
Merged. Thanks for this work, Gokce! 🌟

**Comment by sjackman** [comment]
@gokcedilek Should this file `data/f1.indexlr.head1000.physlr.tsv` be stored in GitHub?

**Comment by gokcedilek** [comment]
I used that file as a small test case (first 1000 entries), however we can modify the Makefile to use the same test file as the other checks.

**Comment by sjackman** [comment]
That file `src/data/f1.indexlr.head1000.physlr.tsv` would be fine, but it's not checked into GitHub, and I can't find it in your home directory `find /home/gdilek -name f1.indexlr.head1000.physlr.tsv`. Could you please add it to GitHub?

**Pull request merged**
