### PR TITLE
added sample test file

### PR DESCRIPTION
**Pull request by gokcedilek**

### CODE REVIEW

**Comment by gokcedilek** [comment]
I uploaded ```src/data/f1.indexlr.head1000.physlr.tsv``` to here.

**Comment by gokcedilek** [comment]
For the conflicts, I'll do rebase onto origin/master

**Comment by sjackman** [comment]
Merged in PR https://github.com/bcgsc/physlr/pull/54. Thanks, Gokce!

**Comment by sjackman** [comment]
Superseded by PR #54.

**Pull request closed without merging**
