### PR TITLE
Fix an edge case bug

### PR DESCRIPTION
**Pull request by schutzekatze**

### CODE REVIEW

**Comment by sjackman** [comment]
How does this bug affect existing runs?

**Comment by schutzekatze** [comment]
It shouldn't affect them the output of any runs.  It was an edge case in which input worker, after arriving at EOF, still ends up writing to its buffer (an empty block) and messes up the read counter, causing an assertion to fail.

**Comment by lcoombe** [comment]
This was the error message I was seeing, just to have it documented:
```physlr-indexlr: ./include/indexlr-workers.h:293: void MinimizeWorker::work(): Assertion `reads.dataCounter - 1 < sizeof(reads.data) / sizeof(reads.data[0])' failed.```

**Comment by schutzekatze** [comment]
Tested with chr4 fly reads, output is the same as before the pull request.

**Comment by lcoombe** [comment]
Thank you for the quick fix, @schutzekatze!

**Pull request merged**
